In [1]:
import numpy as np

In [20]:
def characteristic_matrix(n,t,vac_lambda):
    m = np.zeros((2,2), dtype=complex);
    Yo = 2.6544e-3;

    delta = 2*np.pi*n*t/vac_lambda;
    eta_r = Yo * n;
    m[0,0] = np.cos(delta);
    m[1,1] = np.cos(delta);
    m[0,1] = 1j*np.sin(delta)/eta_r;
    m[1,0] = 1j*eta_r * np.sin(delta);
    
    return m

In [113]:
def y_stack(vac_lambda , ninc , nsub , n , t ):
    Yo = 2.6544e-3;
    eta0 = ninc * Yo;
    eta_m = nsub * Yo;
    BC = np.array([[1],[nsub*Yo]], dtype=complex);
    # P probably should be the line below
    # P=[np.real(BC[0] * np.conj(BC[1])/2 )[0]];
    P=[]
    for count in range(len(n)-1, -1, -1):
        BC = np.dot(characteristic_matrix(n[count],t[count], vac_lambda), BC);
        P.append( np.real(BC[0] * np.conj(BC[1])/2 )[0])


    B = BC[0];
    C = BC[1];
    
    R = (eta0*B - C)/(eta0*B + C);
    R = np.abs(R)**2
    T = 4 * np.real(eta0*eta_m) / (np.abs(eta0*B+C)**2);
    A = 4 * np.real(eta0*(B*np.conj(C)-eta_m)) / (np.abs(eta0*B+C)**2);
    #print(type(P), P/P[-1])
    if len(P):
        P = P/P[-1]*(1-R); 
    return R, T, A, P

In [114]:
R, T, A, P = y_stack(1550, 1, 1, [1.45, 1.45-0.1j], [200, 200])

In [115]:
R, T, A, P[::-1]

(array([0.03615137]),
 array([0.8047323]),
 array([0.15911632]),
 array([0.96384863, 0.96384863]))

In [98]:
R+A+T

array([1.])

In [99]:
type(P)

list

In [105]:
P/P[-1] * (1-R)

array([0.96384863, 0.96384863])

In [112]:
P * 0.1

TypeError: can't multiply sequence by non-int of type 'float'

In [76]:
import admittance

In [77]:
admittance.stack([1, 1.45, 1.45-0.1j, 1.45, 1], [np.inf, 200, 200, 200, np.inf], 1550)

{'R': array([0.0189624]),
 'T': array([0.86513282]),
 'poynting': array([0.9810376 , 0.9810376 , 0.86513282, 0.86513282])}

In [81]:
R, T, A, P = y_stack(1550, 1, 1.45, [], [])

In [82]:
R, T, A, P

(array([0.03373594]), array([0.96626406]), array([0.]), [])

In [92]:
x = [1,2,3]


In [94]:
x/3

TypeError: unsupported operand type(s) for /: 'list' and 'int'